server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot_backend?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Drive
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL57Dialect